device: auto
gh_proxy: null
input_path:
output_path: "D:\\2024\u79CB\\\u8F6F\u4EF6\u5DE5\u7A0B\\Final2x-core\\assets"
pretrained_model_name: RealESRGAN_AnimeJaNai_HD_V3_Compact_2x.pth
target_scale: null
